version: "3"
services:
  app:
    container_name: php56-apache24
    build: .
    volumes:
      - ./docker/php/php.ini:/etc/php/5.6/apache2/conf.d/php.ini
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      - ENVIRONMENT=local
      - MAIL_SERVICE=[mail]:1025
    networks:
      - my-network1

  db:
    container_name: php56-apache24-mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./docker/db.data:/var/lib/mysql
      - ./docker/db.initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - my-network1

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    networks:
      - my-network1

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - my-network1

networks:
  my-network1:
